# Generated by Django 5.0.2 on 2024-02-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpcode', models.CharField(max_length=50)),
                ('tpname', models.CharField(max_length=50)),
                ('tfile', models.ImageField(upload_to='images/')),
                ('tprice', models.IntegerField()),
                ('tstock', models.IntegerField()),
            ],
        ),
    ]
