# Generated by Django 5.0.2 on 2024-03-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=10)),
                ('phoneno', models.IntegerField()),
                ('psw', models.IntegerField()),
                ('cpws', models.IntegerField()),
            ],
        ),
    ]
