# Generated by Django 5.0.2 on 2024-03-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_usreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='usreg',
            name='un',
            field=models.CharField(default='v', max_length=40),
        ),
    ]
