# Generated by Django 5.0.2 on 2024-03-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_usreg_un'),
    ]

    operations = [
        migrations.AddField(
            model_name='usreg',
            name='rights',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
