# Generated by Django 4.0.3 on 2024-03-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_usreg_rights'),
    ]

    operations = [
        migrations.CreateModel(
            name='adreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('un', models.CharField(max_length=40)),
                ('psw', models.IntegerField()),
            ],
        ),
    ]
