# Generated by Django 4.0.3 on 2024-03-16 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_adreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slno', models.IntegerField()),
                ('pname', models.CharField(max_length=40)),
                ('rate', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('total', models.IntegerField()),
                ('userid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('ph', models.CharField(max_length=50)),
                ('feed', models.CharField(max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name='onlinemaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesno', models.IntegerField()),
                ('salesdate', models.DateField(default=datetime.date.today)),
                ('userid', models.IntegerField()),
                ('uname', models.CharField(max_length=30)),
                ('shipment', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=10)),
                ('cardno', models.CharField(max_length=40)),
                ('total', models.IntegerField()),
                ('status', models.CharField(default='New Order', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='onlinesub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesno', models.IntegerField()),
                ('slno', models.IntegerField()),
                ('pname', models.CharField(max_length=40)),
                ('rate', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
