# Generated by Django 5.1.7 on 2025-04-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_cart_feedback_onlinemaster_onlinesub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usreg',
            name='cpws',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usreg',
            name='psw',
            field=models.CharField(max_length=20),
        ),
    ]
