# Generated by Django 5.1.15 on 2026-02-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_usreg_cpws_alter_usreg_psw'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Generic', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('smart', 'Smart Watch'), ('luxury', 'Luxury Watch'), ('sport', 'Sport Watch'), ('casual', 'Casual Watch')], default='smart', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex')], default='unisex', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='strap_material',
            field=models.CharField(choices=[('leather', 'Leather'), ('metal', 'Metal'), ('silicone', 'Silicone')], default='leather', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='tpname',
            field=models.CharField(max_length=100),
        ),
    ]
